import { Header } from "@/components/Header/Header"
import "../Sass/styles.scss"
import "leaflet/dist/leaflet.css"
import { FavoritesContextProvider } from "Context/FavoritesContextProvider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html lang="en">
      <body>
            <FavoritesContextProvider>
              <Header />
              {children}
            </FavoritesContextProvider>
      </body>
    </html>
  )
}
