import { Header } from "@/components/Header"
import "../Sass/styles.scss"
import "leaflet/dist/leaflet.css"
import { HighlightsProvider } from "Context/HighlightsProvider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html lang="en">
      <body>
          {/* VER SI REALMENETE TODOS LO NECESITAN*/}
            <HighlightsProvider>
              <Header />
              {children}
            </HighlightsProvider>
      </body>
    </html>
  )
}
